### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by benzon** [d0p3t/MailDelivery#1]
Add a option to input a different car for the job, so we can use custom mail vans.

And maybe change from using convars to a ini file insted, just to keep our server.cfg clean :D

**Comment by d0p3t** [comment]
I've had people wanting to be able to define their own vehicle to use for this job. **I will be adding this feature.**

As for configurations, I would like to keep this in ConVars as using another file like `.ini` creates extra overhead that is unnecessary. ConVars is more simple and keeps all your settings in just one file (`server.cfg`). You also are not required to use these ConVars unless you are unhappy with the default values as noted in the FiveM forum topic.

What I will be doing is removing the need to load the ConVars server side as calling ConVars client side is now supported.

![image](https://user-images.githubusercontent.com/11293676/46906924-1cd34d80-cf0b-11e8-96ca-d43667f6a8bc.png)

**Comment by benzon** [comment]
Oh just remember to make sure all call's with prices for delivery are called server side so there is no injection point.

**Comment by d0p3t** [comment]
> Oh just remember to make sure all call's with prices for delivery are called server side so there is no injection point.

Security for no injection server side has to be handled by yourself when you listen for the payment/rental events. You can get the min/max payment Convars and check whether the payment falls in the range.

> Add a option to input a different car for the job, so we can use custom mail vans.

This is now possible in v1.0.1. See: https://github.com/d0p3t/MailDelivery/releases/tag/v1.0.1

I will close this issue now as all ideas have been addressed.

**Comment by SavageFlyer420** [comment]
i know this is a long shot and probly outdated standalone resource but seems like it would be good for my small none esx will this work cause i cant seem to figure it out   download the resource through the link  add start i used ensure maildelivery-master added to server.cfg but it loads but nothing is this for esx?  it starts and all could  i get some help fam 
![help](https://user-images.githubusercontent.com/106446855/173624299-b1241f92-fc9c-40ec-8227-b8fc491f9d28.png)
